"""Opening each framework's own development UI from the platform.

Every framework ships a playground, and each one wants its own entry files: ADK
wants a folder per app exposing an ``App``, LangGraph wants a ``langgraph.json``
pointing at graph factories. Writing those by hand means they drift from the
manifests and you end up debugging an agent that is not the one that runs.

So they are generated from the manifests, every time, and then the framework's
own command is launched. What you see in the playground is what ``agentctl run``
would run.

One thing worth knowing before you rely on it: ADK's playground is served
entirely from your machine, while LangGraph serves the API locally and the
Studio front-end lives at smith.langchain.com and connects back to it. On a
network that blocks that, the API is still up and usable — the UI is not.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from agent_core.errors import ConfigError

#: Everything generated lands here, out of the way of what a person writes.
GENERATED_DIR = ".agent-platform"

#: Runtimes served by `langgraph dev`. LangChain 1.x builds its agents on top of
#: LangGraph — `create_agent` returns a CompiledStateGraph — so one server and
#: one UI cover both.
_LANGGRAPH_FAMILY = ("langgraph", "langchain")

_GENERATED_HEADER = '''"""GENERATED by `agentctl ui` — do not edit.

Every graph here is built from the manifests in this repository, so the
playground shows the same agent `agentctl run` would run.
"""
'''


def launch(factory: Any, runtime: str, *, agent: str | None, port: int | None) -> int:
    """Generate what the framework's UI needs and start it."""
    root = factory.store.root
    if not any(os.getenv(name) for name in ("GOOGLE_API_KEY", "GEMINI_API_KEY")):
        print(
            "AVISO: no hay GOOGLE_API_KEY (ni en el entorno ni en .env). El playground\n"
            "       enseña los agentes y sus grafos, pero cada mensaje fallará al\n"
            "       llamar al modelo. Ponla en .env y vuelve a arrancar.\n",
            file=sys.stderr,
        )

    if runtime == "adk":
        return _launch_adk(root, factory, agent=agent, port=port)
    if runtime in _LANGGRAPH_FAMILY:
        return _launch_langgraph(root, factory, runtime=runtime, port=port)

    raise ConfigError(
        f"no UI wired for runtime '{runtime}'. Known: adk, {', '.join(_LANGGRAPH_FAMILY)}."
    )


def _launch_adk(root: Path, factory: Any, *, agent: str | None, port: int | None) -> int:
    """`adk web` over one app per manifest, each carrying the platform's plugins.

    `adk web` takes a directory of apps and lists them in its dropdown. One
    generated folder per agent and workflow makes the whole catalogue
    selectable, and exposing an ``App`` (not a bare ``root_agent``) is what
    makes ADK run the enforcement plugins — guardrails, permissions, policy and
    audit — in the playground exactly as ``agentctl run`` does.
    """
    store = factory.store
    names = [*store.list_agents(), *store.list_workflows()]

    apps = root / GENERATED_DIR / "adk_apps"
    shutil.rmtree(apps, ignore_errors=True)  # a removed manifest leaves no stale app
    for name in names:
        folder = apps / _identifier(name)
        folder.mkdir(parents=True)
        (folder / "__init__.py").write_text("from . import agent\n", encoding="utf-8")
        (folder / "agent.py").write_text(_adk_module(name, factory.environment), encoding="utf-8")

    command = ["adk", "web", str(apps)]
    if port:
        command += ["--port", str(port)]

    selected = _identifier(agent) if agent else None
    url = f"http://127.0.0.1:{port or 8000}/dev-ui/" + (f"?app={selected}" if selected else "")
    print(
        f"ADK Dev UI · {len(names)} apps (una por manifiesto) · entorno {factory.environment}\n"
        f"Abre {url}\n"
        f"Guardrails, permisos, política y auditoría activos, como en `agentctl run`.\n"
    )
    return _run(command, cwd=root, env=dict(os.environ))


def _adk_module(name: str, environment: str) -> str:
    """The module `adk web` loads for one app: an ``App`` built from the manifest."""
    return f'''{_GENERATED_HEADER}
from pathlib import Path

from agent_runtime import load_platform

# <root>/.agent-platform/adk_apps/<app>/agent.py -> <root>
ROOT = Path(__file__).resolve().parents[3]

_factory = load_platform(root=ROOT, environment="{environment}", runtime="adk")
_result = _factory.build("{name}")

#: What `adk web` picks up first: the agent plus the platform's plugin stack.
app = _factory.runtime("adk").app(_result)

#: For tools that only understand the bare agent.
root_agent = _result.agent
'''


def _launch_langgraph(root: Path, factory: Any, *, runtime: str, port: int | None) -> int:
    """`langgraph dev`, over a config and graph module generated from the manifests."""
    store = factory.store
    names = [*store.list_agents(), *store.list_workflows()]

    module = root / GENERATED_DIR / "langgraph_app" / "graphs.py"
    module.parent.mkdir(parents=True, exist_ok=True)
    module.write_text(_graph_module(runtime, factory.environment, names), encoding="utf-8")

    config = root / "langgraph.json"
    config.write_text(
        json.dumps(
            {
                "dependencies": ["."],
                "graphs": {
                    name: f"./{GENERATED_DIR}/langgraph_app/graphs.py:{_identifier(name)}"
                    for name in names
                },
                "env": ".env",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    command = ["langgraph", "dev"]
    if port:
        command += ["--port", str(port)]

    print(
        f"LangGraph Studio · runtime '{runtime}' · entorno {factory.environment}\n"
        f"Generados {config.name} y {module.relative_to(root)} con {len(names)} grafos.\n"
        f"El servidor es local; la UI de Studio se sirve desde smith.langchain.com y se\n"
        f"conecta a él. Si tu red lo bloquea, usa --no-browser y habla con la API directamente.\n"
    )
    return _run(command, cwd=root, env=dict(os.environ))


def _graph_module(runtime: str, environment: str, names: list[str]) -> str:
    """A factory per manifest, over graphs built once when the module is imported.

    Building reads manifests from disk. `langgraph dev` calls the factories from
    inside its event loop, where that counts as a blocking call; import time does
    not. A manifest that fails to build fails only its own graph, when asked for.
    """
    factories = "\n\n".join(
        f'def {_identifier(name)}(config=None):\n'
        f'    """Graph for `{name}`, built from its manifest."""\n'
        f'    return _graph("{name}")'
        for name in names
    )
    return (
        f'{_GENERATED_HEADER}\n'
        f'from pathlib import Path\n\n'
        f'from agent_runtime import load_platform\n\n'
        f'# <root>/.agent-platform/langgraph_app/graphs.py -> <root>\n'
        f'ROOT = Path(__file__).resolve().parents[2]\n'
        f'RUNTIME = "{runtime}"\n'
        f'ENVIRONMENT = "{environment}"\n'
        f'NAMES = {names!r}\n\n'
        f'_factory = load_platform(root=ROOT, environment=ENVIRONMENT, runtime=RUNTIME)\n'
        f'_built = {{}}\n'
        f'for _name in NAMES:\n'
        f'    try:\n'
        f'        _built[_name] = _factory.build(_name).agent\n'
        f'    except Exception as _exc:  # reported when that graph is requested\n'
        f'        _built[_name] = _exc\n\n\n'
        f'def _graph(name):\n'
        f'    built = _built[name]\n'
        f'    if isinstance(built, Exception):\n'
        f'        raise built\n'
        f'    return built\n\n\n'
        f'{factories}\n'
    )


def _identifier(name: str) -> str:
    return name.replace("-", "_")


def _executable(name: str) -> str | None:
    """Find a command, looking inside this interpreter's environment first.

    ``agentctl`` is usually run as ``.venv/bin/agentctl``, which does not put
    ``.venv/bin`` on PATH. Without this, launching the UI of a framework that is
    installed right next to us would fail with "not installed".
    """
    beside = Path(sys.executable).parent / name
    if beside.exists():
        return str(beside)
    return shutil.which(name)


def _run(command: list[str], *, cwd: Path, env: dict[str, str]) -> int:
    """Hand the terminal over to the framework's own command."""
    executable = _executable(command[0])
    if executable is None:
        print(
            f"error: '{command[0]}' no está instalado en este entorno.\n"
            f"       Instálalo y vuelve a intentarlo.",
            file=sys.stderr,
        )
        return 2

    try:
        return subprocess.call([executable, *command[1:]], cwd=cwd, env=env)
    except KeyboardInterrupt:  # pragma: no cover - interactive
        return 0
